// PDF Export utility using browser print functionality
export const exportToPDF = (content: string, filename: string) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Could not open print window. Please allow popups.');
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${filename}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          color: #333;
        }
        h1 { color: #0d9488; margin-bottom: 20px; }
        h2 { color: #374151; margin-top: 30px; margin-bottom: 10px; }
        h3 { color: #6b7280; margin-top: 20px; }
        .section { margin-bottom: 30px; }
        .badge { 
          display: inline-block;
          background: #f3f4f6;
          padding: 2px 8px;
          border-radius: 4px;
          font-size: 12px;
          margin-right: 5px;
          margin-bottom: 5px;
        }
        .warning { 
          background: #fef3c7;
          border-left: 4px solid #f59e0b;
          padding: 10px 15px;
          margin: 15px 0;
        }
        .danger { 
          background: #fee2e2;
          border-left: 4px solid #ef4444;
          padding: 10px 15px;
          margin: 15px 0;
        }
        ul { padding-left: 20px; }
        li { margin-bottom: 5px; }
        .footer { 
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          font-size: 12px;
          color: #9ca3af;
        }
        @media print {
          body { padding: 20px; }
        }
      </style>
    </head>
    <body>
      ${content}
      <div class="footer">
        Generated by AcuPharm - ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load then print
  printWindow.onload = () => {
    printWindow.print();
  };
};

export const formatDrugForExport = (drug: {
  name: string;
  genericName: string;
  class: string;
  category: string;
  uses: string[];
  mechanism: string;
  dosage: string;
  administration: {
    route: string;
    timing: string;
    withFood: boolean;
    reason: string;
  };
  sideEffects: string[];
  contraindications: string[];
  warnings: string[];
  halfLife: string;
  onsetOfAction: string;
}, notes?: string): string => {
  return `
    <h1>${drug.name}</h1>
    <p><strong>Generic Name:</strong> ${drug.genericName}</p>
    <p><strong>Class:</strong> ${drug.class} | <strong>Category:</strong> ${drug.category}</p>
    
    <div class="section">
      <h2>Pharmacokinetics</h2>
      <p><strong>Half-life:</strong> ${drug.halfLife}</p>
      <p><strong>Onset of Action:</strong> ${drug.onsetOfAction}</p>
    </div>
    
    <div class="section">
      <h2>Uses</h2>
      <ul>
        ${drug.uses.map(use => `<li>${use}</li>`).join('')}
      </ul>
    </div>
    
    <div class="section">
      <h2>Mechanism of Action</h2>
      <p>${drug.mechanism}</p>
    </div>
    
    <div class="section">
      <h2>Administration</h2>
      <p><strong>Route:</strong> ${drug.administration.route}</p>
      <p><strong>Timing:</strong> ${drug.administration.timing}</p>
      <p><strong>With Food:</strong> ${drug.administration.withFood ? 'Yes' : 'No'}</p>
      <p><strong>Reason:</strong> ${drug.administration.reason}</p>
    </div>
    
    <div class="section">
      <h2>Dosage</h2>
      <p>${drug.dosage}</p>
    </div>
    
    <div class="section">
      <h2>Side Effects</h2>
      <div>
        ${drug.sideEffects.map(se => `<span class="badge">${se}</span>`).join('')}
      </div>
    </div>
    
    ${drug.contraindications.length > 0 ? `
    <div class="section danger">
      <h2>Contraindications</h2>
      <ul>
        ${drug.contraindications.map(c => `<li>${c}</li>`).join('')}
      </ul>
    </div>
    ` : ''}
    
    ${drug.warnings.length > 0 ? `
    <div class="section warning">
      <h2>Warnings</h2>
      <ul>
        ${drug.warnings.map(w => `<li>${w}</li>`).join('')}
      </ul>
    </div>
    ` : ''}
    
    ${notes ? `
    <div class="section">
      <h2>Personal Notes</h2>
      <p>${notes.replace(/\n/g, '<br>')}</p>
    </div>
    ` : ''}
  `;
};

export const formatNotesForExport = (notes: { drugName: string; note: string }[]): string => {
  return `
    <h1>My Drug Notes</h1>
    ${notes.map(n => `
      <div class="section">
        <h2>${n.drugName}</h2>
        <p>${n.note.replace(/\n/g, '<br>')}</p>
      </div>
    `).join('')}
  `;
};
