-- Spaced repetition table with SM-2 algorithm fields
CREATE TABLE public.spaced_repetition (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    drug_id text NOT NULL,
    card_index integer NOT NULL,
    ease_factor numeric DEFAULT 2.5,
    interval_days integer DEFAULT 1,
    repetitions integer DEFAULT 0,
    next_review_date timestamp with time zone DEFAULT now(),
    last_review_date timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, drug_id, card_index)
);

ALTER TABLE public.spaced_repetition ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own spaced repetition"
ON public.spaced_repetition FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Study reminders table
CREATE TABLE public.study_reminders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    reminder_time time NOT NULL,
    days_of_week integer[] DEFAULT '{1,2,3,4,5,6,7}',
    is_enabled boolean DEFAULT true,
    last_sent timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.study_reminders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own reminders"
ON public.study_reminders FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Quiz analytics - detailed question-level tracking
CREATE TABLE public.quiz_question_analytics (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    quiz_id text NOT NULL,
    question_index integer NOT NULL,
    category text NOT NULL,
    is_correct boolean NOT NULL,
    time_spent_seconds integer,
    answered_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.quiz_question_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own analytics"
ON public.quiz_question_analytics FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Study plans generated by AI
CREATE TABLE public.study_plans (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    description text,
    focus_areas text[],
    daily_goals jsonb,
    duration_days integer DEFAULT 7,
    start_date date DEFAULT CURRENT_DATE,
    is_active boolean DEFAULT true,
    progress jsonb DEFAULT '{}',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own study plans"
ON public.study_plans FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- AI generated quizzes
CREATE TABLE public.generated_quizzes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    focus_topics text[],
    questions jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.generated_quizzes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own generated quizzes"
ON public.generated_quizzes FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create index for faster spaced repetition queries
CREATE INDEX idx_spaced_repetition_next_review ON public.spaced_repetition(user_id, next_review_date);
CREATE INDEX idx_quiz_analytics_category ON public.quiz_question_analytics(user_id, category);